version: '3.8'

services:
  db:
    image: postgres:alpine
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
    volumes:
      - 'pg-data:/var/lib/postgresql/data'

volumes:
  pg-data: